play_cmd='(function (){document.querySelector(".ply").click();})()'
prev_cmd='(function (){document.querySelector(".prv").click();})()'
next_cmd='(function (){document.querySelector(".nxt").click();})()'
get_title_cmd='(function (){return document.querySelector("a.fc1").text;})()'
get_artist_cmd='(function (){return document.querySelector("span.by").firstChild.title;})()'
open_fav_cmd='(function (){document.querySelector("a.icn-add").click();})()'
add_fav_cmd='(function (){document.querySelector("#g_iframe").contentDocument.querySelector(".zcnt .s-fc0").click();})()'
web_url='music.163.com'
